name: cablab
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.5.1=py35_0
- bokeh=0.10.0=py35_0
- bzip2=1.0.6=vc14_2
- chest=0.2.3=py35_0
- click=6.6=py35_0
- cloudpickle=0.2.1=py35_0
- clyent=1.2.2=py35_0
- conda-forge::basemap=1.0.8.dev0=np110py35_2
- conda-forge::geos=3.4.2=vc14_2
- conda-forge::pyproj=1.9.5.1=py35_0
- conda-forge::pyshp=1.2.3=py35_0
- cycler=0.10.0=py35_0
- dask=0.11.0=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- flask=0.11.1=py35_0
- freetype=2.5.5=vc14_0
- h5py=2.6.0=np110py35_0
- hdf5=1.8.15.1=vc14_4
- heapdict=1.0.0=py35_1
- ioos::h5netcdf=0.2.2=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_0
- jpeg=8d=vc14_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=vc14_1
- libtiff=4.0.6=vc14_1
- llvmlite=0.10.0=py35_0
- locket=0.2.0=py35_1
- markupsafe=0.23=py35_1
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.2=py35_0
- mkl=11.3.1=0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- nbpresent=3.0.2=py35_0
- netcdf4=1.2.2=np110py35_0
- networkx=1.11=py35_0
- nose=1.3.7=py35_0
- notebook=4.2.0=py35_0
- numba=0.25.0=np110py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2g=vc14_0
- pandas=0.18.1=np110py35_0
- partd=0.3.6=py35_0
- path.py=8.2=py35_0
- pickleshare=0.5=py35_0
- pillow=3.2.0=py35_0
- pip=8.1.1=py35_1
- pygments=2.1.3=py35_0
- pyparsing=2.1.1=py35_0
- pyqt=4.11.4=py35_5
- pyreadline=2.1=py35_0
- python=3.5.2=0
- python-dateutil=2.5.2=py35_0
- pytz=2016.3=py35_0
- pyyaml=3.11=py35_4
- pyzmq=15.2.0=py35_0
- qt=4.8.7=vc14_7
- qtconsole=4.2.1=py35_0
- requests=2.11.1=py35_0
- scikit-image=0.12.3=np110py35_0
- scipy=0.17.0=np110py35_1
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_2
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- toolz=0.8.0=py35_0
- tornado=4.2.1=py35_1
- traitlets=4.2.1=py35_0
- vs2010_runtime=10.00.40219.1=0
- vs2015_runtime=14.00.23026.0=0
- werkzeug=0.11.10=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- xarray=0.7.2=py35_0
- zlib=1.2.8=vc14_2
- pip:
  - basemap==1.0.8
  - gridtools==0.2.0
  - h5netcdf==0.2.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - pyproj==1.9.5.1
  - pyshp==1.2.3
  - sphinx==1.3.1