name: esdl
channels:
  - conda-forge
  - cablab
  - ioos
dependencies:
  - python <=3.7.4
  - dask
  - gridtools
  - h5netcdf
  - h5py
  - llvmlite
  - netcdf4
  - numba
  - pandas
  - python-dateutil
  - pytz
  - scikit-image
  - setuptools
  - six
  - wheel
  - xarray
  - zarr
  - s3fs
  #
  # for testing only
  #
  - pytest
  - pytest-cov
