name: esdl
channels:
- conda-forge
- bc-dev
- ioos
dependencies:
- python=3.6
- dask >=0.19,<1.0.3
- gridtools=0.4.1
- h5netcdf >=0.4.2,<1.0
- h5py >=2.6.0,<3.0
- llvmlite >=0.13.0,<1.0
- netcdf4 >=1.2,<2.0
- numba >=0.33,<1.0
- numpy >=1.15,<2.0
- pandas >=0.22,<1.0
- python-dateutil >=2.6,<3.0
- pytz >= 2016.6.1
- scikit-image >=0.12.3, <1.0
- setuptools >=27.2.0
- six >=1.10.0,<2.0
- wheel >=0.29.0,<1.0
- xarray >=0.10.3,<1.0
- zarr >=2.2.0,<3.0
#
# for testing only
#
- pytest >=3.1,<3.2
- pytest-cov >=2.5.1,<2.6
- flake8
