name: esdl
channels:
  - conda-forge
  - cablab
  - ioos
dependencies:
  - python =3.6
  - dask >=0.19,<1.0
  #- gridtools =0.4.1
  - h5netcdf >=0.4.2,<1.0
  - h5py >=2.8.0,<3.0
  - llvmlite >=0.24.0,<1.0
  - netcdf4 >=1.2,<2.0
  - numba >=0.33,<1.0
  - numpy >=1.15,<2.0
  - pandas >=0.22,<1.0
  - python-dateutil >=2.6,<3.0
  - pytz >=2018.5
  - scikit-image >=0.14.1
  - setuptools >=40.4.3
  - six >=1.11.0
  - wheel >=0.32.0
  - xarray >=0.10.6
  - zarr >= 2.2.0,<3.0
  #
  # for testing only
  #
  - pytest >=3.8.2
  - pytest-cov
  - flake8
