name: esdl
channels:
  - conda-forge
  - cablab
  - ioos
dependencies:
  - dask=1.1.4
  - gridtools=0.4.0.dev
  - h5netcdf=0.7.1
  - h5py=2.9.0
  - llvmlite=0.28.0
  - netcdf4=1.5.0
  - numba=0.43.1
  - pandas=0.24.2
  - pip=9.0.3
  - python=3.6
  - python-dateutil=2.8.0
  - pytz=2018.9
  - s3fs=0.2.0
  - scikit-image=0.14.2
  - setuptools=39.2.0
  - six=1.11.0
  - wheel=0.31.0
  - xarray=0.12.0
  - zarr=2.3.1

  #
  # for testing only
  #
  - pytest
  - pytest-cov
