name: esdl
channels:
- conda-forge
- bc-dev
- ioos
dependencies:
- python=3.6
- dask >=0.19,<1.0.3
- gridtools=0.4.1
- h5netcdf >=0.4.2,<1.0
- h5py
- llvmlite
- netcdf4 >=1.2,<2.0
- numba >=0.33,<1.0
- pandas >=0.22,<1.0
- python-dateutil >=2.6,<3.0
- pytz
- scikit-image
- setuptools
- six
- wheel
- xarray
- zarr
#
# for testing only
#
- pytest >=3.1,<3.2
- pytest-cov >=2.5.1,<2.6
- flake8
